import Head from 'next/head'

import BoardList from '@/components/units/board/list/BoardList.container'

export default function Home() {
  return (
    <>
      <Head>
        <title>자유게시판</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <BoardList />
      </main>
    </>
  )
}
